import "@/app/_styles/globals.css";

import type { Metadata } from "next";

import Footer from "./_components/Footer";

import Header from "./_components/Header";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GreenShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Header />
        </header>

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
