import "@/app/_styles/globals.css";

import type { Metadata } from "next";

import Footer from "./_components/Footer";

import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "GreenShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header />
        </header>

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
